---
- functions:
  - {name: unsafePerformIO, within: []}  # unsafePerformIO can appear nowhere
  - {name: error, within: []}  # throw real errors
  - {name: undefined, within: []}
  - {name: fromJust, within: []}  # this is hell to track down
  - {name: foldl, within: []}  # foldl has bad properties
- error: {lhs: "hylo embed", rhs: "ana", name: "Use anamorphism"}
- error: {lhs: "hylo f project", rhs: "cata f", name: "Use catamorphism"}
- error: {lhs: "do { x <- y ; pure (f x) }", rhs: "f =<< f", name: "Avoid do-notation"}
- error: {lhs: "concat", rhs: "join", name: "Generalize concat"}
- error: {lhs: "concatMap", rhs: "(=<<)", name: "Generalize concatMap"}
- error: {lhs: "f >> pure ()", rhs: "void f", name: "Use void"}
- ignore: {name: Use <$>, within: [ Language.ATS.PrettyPrint ]}
- ignore: {name: Unused LANGUAGE pragma, within: [ Language.ATS.PrettyPrint ]}
- ignore: {name: Functor law, within: [ Language.ATS.PrettyPrint ]}
