---
sudo: false
cache:
  directories:
    - $HOME/.stack
addons:
  apt:
    packages:
      - libgmp3-dev
matrix:
  include:

    # Linux
    - env: TARGET=x86_64-unkown-linux-gnu
      language: python

    # OS X
    - env: TARGET=x86_64-apple-darwin
      os: osx
      language: default

  allow_failures:
    - env: TARGET="x86_64-apple-darwin"

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - |
    if [ `uname` = "Darwin" ]
    then
      curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    else
      curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
  - chmod a+x ~/.local/bin/stack
  - |
    if [ `uname` = "Linux" ]
    then
      pip install yamllint
    else
      echo "skipping yaml verification..."
    fi

install:
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  - stack --no-terminal build --haddock --no-haddock-deps
  - stack test --no-run-tests
  - curl -sL https://raw.githubusercontent.com/vmchale/tomlcheck/master/sh/check | sh -s .atsfmt.toml
  - |
    if [ `uname` = "Linux" ]
    then
      yamllint stack.yaml
      yamllint appveyor.yml
      yamllint .yamllint
      yamllint .travis.yml
      yamllint .hlint.yaml
      yamllint .stylish-haskell.yaml
      # curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s src app test bench
      # curl -sL https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh | sh -s src app test bench
    else
      echo "skipping yaml verification..."
    fi
  - stack build --test --bench --no-run-tests --no-run-benchmarks
  - |
    if [ `uname` = "Darwin" ]
      find .stack-work -name atsfmt -perm 755
    else
      echo 'nothing'
    fi
  - |
    if [ `uname` = "Darwin" ]
    then
      export BINPATH="$(find .stack-work -name atsfmt -perm 755 | tail -n1)"
    else
      export BINPATH="$(find -name atsfmt -executable | tail -n1)"
    fi
  - echo $BINPATH
  - mv $BINPATH atsfmt-$TARGET
  - ls atsfmt-$TARGET

deploy:
  api_key:
    secure: "STSYpNRgAF+w51ncDr95/KiASc1tTj+kEyDmz+uLZlU3VoB3m6YNZClKDGG/UHPpOI08rkliLZzao5nNGs/IgBjOGZEQ5ybZPpMU8+ooUKbR+GCR+7BqbegJotlHKgl2EB6+qVv94mpZiHwUTnX/MJBxnnixqXfGiILlUM3QE/bDbFdPfnaLlX/Kp5GgEiruryWpaJkTnoeK7jmmxdV7k6+BRtSLz9/8Uyn+UC96Z3tCzEB8E6DBCbzGXy2dsGXqyEfUUvBcVWRhgfMyAQp33qv1b9ERZhgHO7qjwdGUGwYJzIdXaVJGcz1mnNU3giH/XAewzu4TeSPNrby+9CrHsbS2Vr13rnGUt6dyKQE6ez+fRRLfOj6yOj+mNlO2AHmKphtp8R90HnrKivxszLcWNOvP2nLIaY2/hqdMAfbojO+dmXBmNxtaaq9NuH9qtrh62cCMCqtGteEREcfd0vO83vw2wRYkhBpQ1dBh88f3DBPZl+IQk228Ort3F8ZHpLMvHvvuc0tQORmad0YC/WsUjbyzQbJP9phgz7r2vRgbla46u3CElwNhMd5uglgmz9cNXizCFeQLtk9aZWE9YtOtVcqg9uEH0rmtWzf2RFeZb+PbMt709wMs9pae734p2G8aikz7MHqIPO27a3lbJ1I9d7ZFyq6SdtpdS1e3ziTmWDk="
  file: atsfmt-$TARGET
  on:
    tags: true
  provider: releases
  skip_cleanup: true

branches:
  only:
    - /\d+\.\d+\.\d+\.\d+.*$/
    - master
