sudo: false
cache:
  directories:
  - "$HOME/.stack"
addons:
  apt:
    packages:
    - libgmp3-dev
matrix:
  include:
  - env: TARGET=x86_64-unkown-linux-gnu
    language: python
  - env: TARGET=x86_64-apple-darwin
    os: osx
    language: default
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- |
  if [ `uname` = "Darwin" ]
  then
    curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi
- chmod a+x ~/.local/bin/stack
- |
  if [ `uname` = "Linux" ]
  then
    pip install yamllint
  else
    echo "skipping yaml verification..."
  fi
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- stack --no-terminal build --haddock --no-haddock-deps
- stack test --no-run-tests
- |
  if [ `uname` = "Linux" ]
  then
    yamllint stack.yaml
    yamllint appveyor.yml
    yamllint .travis.yml
  else
    echo "skipping yaml verification..."
  fi
- stack bench --no-bench
- curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
- curl -sL https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh | sh -s
  .
- |
  if [ `uname` = "Darwin" ]
  then
    export BINPATH="$(find . -name atsfmt -perm 755 | tail -n1)"
  else
    export BINPATH="$(find -name atsfmt -executable | tail -n2 | head -n1)"
  fi
- echo $BINPATH
- mv $BINPATH atsfmt-$TARGET
- ls atsfmt-$TARGET
deploy:
  api_key:
    secure: Ud5v7q994U9Nl0osERMA69l0B6KgqN8GYtycoQ2up/bBa/4dWUpztHdZHnO77hs27jyFdivCpgtp6H/xWDSpHDp1oVd0Z7JwEBsGz4f+jw8wH9rjzdgxEpAXQEep4xNgD7DaeHuX8JCWQDaKxvFJ/4i4aS7MJR9FQJ1mR52d8nO0un10/c7PpumlIEW/xBRPlYgVWy334rGG0IkejyF9VbweIGtPVGB0sw9Tn8HRGiDfr0Izct/hlpTN22PBLZ4dZFpfe/UUbxqdY4b7TDqkqgdO7pngv42uCBucXWXY4mZMr89WAiL3r67hmQgiu4Dp2bM3DcKpFn+Sd0hCk/rd3NxIsYwD+gF0eviK+dhDJTscfNXnHIDIAXXy/pFqT7EYfQyhbfXtKKFcfNhCLCm0gSi4RdwZ+gOVyfNEiETcME6HTBUdARZr9PEBSA8dAiD0GZh7ZLKnsdnc/qXV2lCNi2RvNKGVZOhvMMXHv5QrC6h+EDy3RNYPRQCXzSLba25KAHL4coxUrflcp56lDeid5BNUlR7H9EYq1V0ZzQNPy04uhW7tEQOJjfSI+XNgmyPfSih7FWLS6gYBmK4DIwzh/jpJL0J3WlrUjghk7ZyBQXwGStkOrEpvYxQDkORm38xSIk8BffAo+oGka6/kQEZDPxIbD4uMxqhVjMLLVaKT+mc=
  file: atsfmt-$TARGET
  on:
    tags: true
  provider: releases
  skip_cleanup: true
branches:
  only:
  - "/\\d+\\.\\d+\\.\\d+\\.\\d+.*$/"
  - master
