- package:
  - name: ats-format
  - section:
    - name: library
    - message:
      - name: Weeds exported
      - module:
        - name: Language.ATS.Types
        - identifier:
          - constructorUniversals
          - leaves

