---
resolver: lts-10.4
packages:
  - '.'
extra-deps:
  - ansi-wl-pprint-0.6.8.2
  - htoml-megaparsec-1.1.0.1
  - composition-prelude-1.1.0.2
  - dirstream-1.0.3
  - hspec-dirstream-0.3.0.0
  - cli-setup-0.1.0.3
  - language-ats-0.2.0.5
flags:
  ats-format:
    development: false
extra-package-dbs: []
