---
resolver: lts-10.0
packages:
  - '.'
extra-deps:
  - ansi-wl-pprint-0.6.8.1
  - htoml-megaparsec-1.0.1.11
  - composition-prelude-0.1.1.1
  - dirstream-1.0.3
flags:
  ats-format:
    development: false
extra-package-dbs: []
