---
resolver: lts-10.2
packages:
  - '.'
extra-deps:
  - ansi-wl-pprint-0.6.8.1
  - htoml-megaparsec-1.0.1.12
  - composition-prelude-0.1.1.4
  - dirstream-1.0.3
  - hspec-dirstream-0.1.0.1
flags:
  ats-format:
    development: false
extra-package-dbs: []
